name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{secrets.SERVER_HOST}}
      SERVER_USER: ${{secrets.SERVER_USER}}
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
      - name: deploy 
        run: | 
          echo "${SSH_KEY}" > ssh_key.pem
          chmod 400 ssh_key.pem

          ssh -i my_ssh_key.pem -o StrictHostKeyChecking=no "${SERVER_HOST}"@"${SERVER_USER}" << 'EOF'
              set -e 
              cd /home/ubuntu/app
              git pull origin main 
              sudo docker compose down 
              sudo docker compose up -d --build 
            EOF
        
      - name: Clean up SSH key 
        run: rm my_ssh_key.pem
